const KEY="repforge_v1",DRAFT="repforge_draft_v1";
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const uid=()=>crypto?.randomUUID?.()||`id_${Date.now()}_${Math.random().toString(36).slice(2)}`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmt=v=>Number.isFinite(Number(v))?(Number.isInteger(Number(v))?String(Number(v)):Number(v).toFixed(2).replace(/\.?0+$/,"")):"";
const avg=a=>a.length?a.reduce((s,x)=>s+Number(x||0),0)/a.length:0;
const sum=a=>a.reduce((s,x)=>s+Number(x||0),0);
const muscles=s=>String(s||"").split(",").map(x=>x.trim()).filter(Boolean);
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add("hidden"),2200)};
const download=(text,name,type="text/plain")=>{const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(u)};
const program=[
["Day 1",1,"Hack squat or pendulum squat",2,4,8,"Quads","Glutes,Adductors"],["Day 1",2,"Seated leg curl",2,4,8,"Hamstrings",""] ,["Day 1",3,"Incline converging chest press",2,4,8,"Chest","Front delts,Triceps"],["Day 1",4,"Chest-supported machine row",2,4,8,"Mid/upper back","Lats,Rear delts,Biceps"],["Day 1",5,"Machine lateral raise",2,6,8,"Side delts",""] ,["Day 1",6,"Hip adduction machine",2,6,8,"Adductors",""] ,
["Day 2",1,"45 degree leg press, quad-biased",2,4,8,"Quads","Glutes,Adductors"],["Day 2",2,"Smith machine RDL or machine hip hinge",2,4,8,"Hamstrings,Glutes","Spinal erectors"],["Day 2",3,"Machine shoulder press",2,4,8,"Front delts","Side delts,Triceps"],["Day 2",4,"Neutral-grip pulldown",2,4,8,"Lats","Mid/upper back,Biceps"],["Day 2",5,"Pec deck",2,6,8,"Chest",""] ,["Day 2",6,"Machine preacher curl",2,6,8,"Biceps",""] ,
["Day 3",1,"Leg extension",2,6,8,"Quads",""] ,["Day 3",2,"Lying or seated leg curl",2,6,8,"Hamstrings",""] ,["Day 3",3,"Machine chest dip or plate-loaded chest press",2,4,8,"Chest","Front delts,Triceps"],["Day 3",4,"Plate-loaded high row",2,4,8,"Lats,Mid/upper back","Rear delts,Biceps"],["Day 3",5,"Reverse pec deck",2,6,8,"Rear delts","Mid/upper back"],["Day 3",6,"Cable pressdown",2,6,8,"Triceps",""]
].map(x=>({id:uid(),day:x[0],order:x[1],name:x[2],sets:x[3],min:x[4],max:x[5],primary:x[6],secondary:x[7]}));
let state=load(),day=days()[0]||"Day 1",installPrompt=null;
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.program&&Array.isArray(s.log))return s}catch{}return{settings:{jumpPct:2.5,minJump:2.5,rirHigh:2},program,log:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function days(){return [...new Set(state.program.map(x=>x.day))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function exercises(d=day){return state.program.filter(x=>x.day===d).sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name))}
function last(name){const r=state.log.filter(x=>x.name===name).sort((a,b)=>String(a.date).localeCompare(b.date)||String(a.created).localeCompare(b.created));if(!r.length)return[];const id=r.at(-1).session;return r.filter(x=>x.session===id).sort((a,b)=>a.set-b.set)}
function round(v){const inc=+state.settings.minJump||2.5;return Math.round(v/inc)*inc}
function recommendation(ex){const l=last(ex.name);if(!l.length)return{text:`No history. Pick a load for ${ex.min}-${ex.max} reps with 0-${state.settings.rirHigh} RIR.`,load:null};const reps=l.map(x=>+x.reps),rirs=l.map(x=>+x.rir),loads=l.map(x=>+x.load).sort((a,b)=>a-b),load=loads[Math.floor(loads.length/2)],minReps=Math.min(...reps),rir=avg(rirs);if(minReps>=ex.max&&rir>=state.settings.rirHigh+1)return{text:"Increase load more aggressively. You topped the range with room left.",load:round(load+Math.max(load*state.settings.jumpPct*2/100,state.settings.minJump))};if(minReps>=ex.max)return{text:"Increase load. You hit the top of the range across all sets.",load:round(load+Math.max(load*state.settings.jumpPct/100,state.settings.minJump))};if(minReps<ex.min)return{text:`Keep or reduce slightly. One set fell below ${ex.min} reps.`,load};return{text:"Keep load and add reps while staying inside target RIR.",load}}
function render(){renderTabs();renderWorkout();renderStats();renderHistory();renderProgram();renderSettings()}
function renderTabs(){const ds=days();if(!ds.includes(day))day=ds[0]||"Day 1";$("#dayTabs").innerHTML=ds.map(d=>`<button type="button" class="${d===day?"active":""}" data-day="${esc(d)}">${esc(d)}</button>`).join("");$$("#dayTabs button").forEach(b=>b.onclick=()=>{day=b.dataset.day;renderTabs();renderWorkout()})}
function renderWorkout(){const draft=JSON.parse(localStorage.getItem(DRAFT)||"{}");$("#workout").innerHTML=exercises().map(ex=>{const r=recommendation(ex),prev=last(ex.name),p=prev.length?`<p class="hint">Previous: ${prev.map(x=>`${fmt(x.load)}x${x.reps}@${fmt(x.rir)}`).join(" · ")}</p>`:"";const rows=Array.from({length:ex.sets},(_,i)=>{const n=i+1,old=prev.find(x=>x.set===n),base=r.load??old?.load??0;return `<div class="setrow"><b>${n}</b><input data-k="${ex.id}_${n}_load" type="number" step="0.5" value="${esc(draft[`${ex.id}_${n}_load`]??fmt(base))}"><input data-k="${ex.id}_${n}_reps" type="number" step="1" value="${esc(draft[`${ex.id}_${n}_reps`]??ex.min)}"><input data-k="${ex.id}_${n}_rir" type="number" step="0.5" value="${esc(draft[`${ex.id}_${n}_rir`]??1)}"></div>`}).join("");return `<article class="exercise"><h3>${esc(ex.name)}</h3><p class="meta">${ex.sets} sets · ${ex.min}-${ex.max} reps · ${esc(ex.primary)}</p>${p}<div class="rec">${esc(r.text)}${r.load!==null?` Suggested: <b>${fmt(r.load)} kg</b>`:""}</div><div class="setrow"><b>Set</b><b>kg</b><b>reps</b><b>RIR</b></div>${rows}</article>`}).join("");$$("#workout input").forEach(i=>i.oninput=()=>{const d={};$$("#workout input").forEach(x=>d[x.dataset.k]=x.value);localStorage.setItem(DRAFT,JSON.stringify(d))})}
function saveWorkout(e){e.preventDefault();const date=$("#date").value||today(),session=`${date}_${day}_${Date.now()}`,notes=$("#notes").value.trim(),created=new Date().toISOString(),rows=[];for(const ex of exercises())for(let n=1;n<=ex.sets;n++)rows.push({session,date,day,name:ex.name,set:n,load:+$(`[data-k="${ex.id}_${n}_load"]`).value||0,reps:+$(`[data-k="${ex.id}_${n}_reps"]`).value||0,rir:+$(`[data-k="${ex.id}_${n}_rir"]`).value||0,notes,created});state.log.push(...rows);save();localStorage.removeItem(DRAFT);$("#notes").value="";toast("Workout saved.");render()}
function summaries(){const m=new Map();for(const x of state.log){const k=`${x.session}|${x.name}`;if(!m.has(k))m.set(k,{session:x.session,date:x.date,day:x.day,name:x.name,loads:[],reps:[],rirs:[],sets:0});const o=m.get(k);o.loads.push(+x.load);o.reps.push(+x.reps);o.rirs.push(+x.rir);o.sets++}return [...m.values()].map(o=>({session:o.session,date:o.date,day:o.day,name:o.name,top:Math.max(...o.loads,0),reps:sum(o.reps),rir:avg(o.rirs),sets:o.sets,volume:avg(o.loads)*sum(o.reps)})).sort((a,b)=>a.date.localeCompare(b.date)||a.session.localeCompare(b.session))}
function renderStats(){const names=[...new Set(state.log.map(x=>x.name))].sort();$("#metrics").innerHTML=[["Sessions",new Set(state.log.map(x=>x.session)).size],["Exercises",names.length],["Sets",state.log.length],["Reps",sum(state.log.map(x=>x.reps))]].map(x=>`<div class="metric"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("");const old=$("#statExercise").value;$("#statExercise").innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join("")||"<option>No data</option>";if(names.includes(old))$("#statExercise").value=old;const rows=summaries().filter(x=>x.name===$("#statExercise").value);draw(rows);$("#recent").innerHTML=table(rows.slice(-8).reverse().map(x=>({Date:x.date,Top:fmt(x.top),Reps:x.reps,RIR:fmt(x.rir),Volume:fmt(x.volume)})));const top=names.map(n=>state.log.filter(x=>x.name===n).sort((a,b)=>b.load-a.load)[0]).filter(Boolean).map(x=>({Exercise:x.name,Date:x.date,kg:fmt(x.load),Reps:x.reps,RIR:fmt(x.rir)}));$("#tops").innerHTML=table(top)}
function draw(rows){const c=$("#chart"),ctx=c.getContext("2d"),w=c.clientWidth||320,h=220,ratio=devicePixelRatio||1;c.width=w*ratio;c.height=h*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle="#2d2d33";ctx.beginPath();ctx.moveTo(36,12);ctx.lineTo(36,h-30);ctx.lineTo(w-10,h-30);ctx.stroke();if(!rows.length){ctx.fillStyle="#a1a1aa";ctx.fillText("No data yet",44,40);return}const max=Math.max(...rows.map(x=>x.top),1),min=Math.min(...rows.map(x=>x.top),0),y=v=>h-30-((v-min)/(max-min||1))*(h-50),x=i=>36+(rows.length===1?(w-56)/2:i*(w-56)/(rows.length-1));ctx.strokeStyle="#f4f4f5";ctx.lineWidth=2.5;ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(x(i),y(r.top)):ctx.moveTo(x(i),y(r.top)));ctx.stroke();ctx.fillStyle="#f4f4f5";rows.forEach((r,i)=>{ctx.beginPath();ctx.arc(x(i),y(r.top),4,0,7);ctx.fill()})}
function renderHistory(){const rows=[...state.log].sort((a,b)=>b.date.localeCompare(a.date)||a.name.localeCompare(b.name)||a.set-b.set).map(x=>({Date:x.date,Day:x.day,Exercise:x.name,Set:x.set,kg:fmt(x.load),Reps:x.reps,RIR:fmt(x.rir)}));$("#historyTable").innerHTML=table(rows);const sessions=[...new Map(state.log.map(x=>[x.session,x])).values()].sort((a,b)=>String(b.created).localeCompare(String(a.created)));$("#sessions").innerHTML=sessions.map(x=>`<div class="session"><div><strong>${esc(x.day)}</strong><p class="hint">${esc(x.date)} · ${state.log.filter(r=>r.session===x.session).length} sets</p></div><button class="danger" data-del="${esc(x.session)}">Delete</button></div>`).join("");$$("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Delete this session?")){state.log=state.log.filter(x=>x.session!==b.dataset.del);save();render();toast("Session deleted.")}})}
function renderProgram(){if(document.activeElement!==$("#programJson"))$("#programJson").value=JSON.stringify(state.program.map(({id,...x})=>x),null,2);const m=new Map();for(const e of state.program){for(const x of muscles(e.primary))addVol(m,x,e.sets,0);for(const x of muscles(e.secondary))addVol(m,x,0,e.sets*.5)}$("#volume").innerHTML=table([...m.entries()].map(([Muscle,v])=>({Muscle,Direct:fmt(v.d),Partial:fmt(v.p),Effective:fmt(v.d+v.p)})).sort((a,b)=>Number(b.Effective)-Number(a.Effective)))}
function addVol(m,k,d,p){if(!m.has(k))m.set(k,{d:0,p:0});m.get(k).d+=d;m.get(k).p+=p}
function saveProgram(){try{state.program=JSON.parse($("#programJson").value).map((x,i)=>({id:uid(),day:x.day||"Day 1",order:+x.order||i+1,name:x.name||"Exercise",sets:+x.sets||2,min:+x.min||4,max:+x.max||8,primary:x.primary||"",secondary:x.secondary||""}));save();day=days()[0]||"Day 1";render();toast("Program saved.")}catch{toast("Invalid JSON.")}}
function renderSettings(){$("#jumpPct").value=state.settings.jumpPct;$("#minJump").value=state.settings.minJump;$("#rirHigh").value=state.settings.rirHigh;$("#storageNote").textContent=`Stored only in this browser under ${KEY}. Export JSON before clearing browser data or changing phones.`}
function table(rows){if(!rows.length)return'<div class="card"><p class="hint">No data yet.</p></div>';const h=Object.keys(rows[0]);return`<table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${h.map(x=>`<td>${esc(r[x])}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function exportCsv(){const h=["session","date","day","name","set","load","reps","rir","notes","created"],csv=[h.join(","),...state.log.map(r=>h.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n");download(csv,`repforge_log_${today()}.csv`,"text/csv")}
function exportJson(){download(JSON.stringify(state,null,2),`repforge_backup_${today()}.json`,"application/json")}
async function importJson(e){const f=e.target.files?.[0];if(!f)return;try{const s=JSON.parse(await f.text());if(!s.program||!Array.isArray(s.log))throw Error();state=s;save();render();toast("Backup imported.")}catch{toast("Invalid backup.")}e.target.value=""}
function init(){if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installBtn").classList.add("hidden")}};$("#date").value=today();$("#logForm").onsubmit=saveWorkout;$("#statExercise").onchange=renderStats;$("#saveProgram").onclick=saveProgram;$("#saveSettings").onclick=()=>{state.settings={jumpPct:+$("#jumpPct").value||2.5,minJump:+$("#minJump").value||2.5,rirHigh:+$("#rirHigh").value||2};save();render();toast("Settings saved.")};$("#exportCsv").onclick=exportCsv;$("#exportJson").onclick=exportJson;$("#importJson").onchange=importJson;$("#reset").onclick=()=>{if(confirm("Delete the training log? Export a backup first if needed.")){state.log=[];save();render();toast("Log deleted.")}};$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.toggle("active",x===b));$$(".view").forEach(v=>v.classList.toggle("active",v.id===b.dataset.view));render()});render()}
init();
