/**
 * A ready-to-log program for browser suites.
 *
 * A device that has not been through onboarding holds no program at all, so a
 * suite that boots a fresh app and then logs, picks days, or opens the workout
 * has to install one first. This is that program: three days of six machine
 * movements, the shape the suites were written against, seeded explicitly
 * instead of harvested from a bundled default that no longer exists.
 *
 * It is a fixture, not a product surface — nothing in the app mints it.
 */

import { readFileSync } from "node:fs";

/*
 * The program is generated by tools/build-seed-program-fixture.mjs through the
 * app's own Build definition: each familiar name below is the display alias of
 * a real catalog movement, and programMeta carries its canonical
 * ProgramDefinition.
 */
const FIXTURE = JSON.parse(readFileSync(new URL("./seed-program-v067.json", import.meta.url), "utf8"));

/**
 * One slot carries alternates on purpose, and carries two kinds: "Leg press" is
 * a seed movement, "Pendulum squat" is not. A picker that only kept the ones
 * it could match would quietly drop the second, so the substitution walk needs
 * both present to notice.
 */
const ALTERNATES = { "Hack squat": ["Leg press", "Pendulum squat"] };

/** The program rows. Stable ids, so a suite can address one across a reload. */
export function seedProgram() {
  return FIXTURE.program.map((source) => {
    const row = structuredClone(source);
    if (ALTERNATES[row.name]) row.alternates = ALTERNATES[row.name].slice();
    return row;
  });
}

/** Its metadata: onboarded, so the app treats it as the lifter's own program. */
export function seedProgramMeta(overrides = {}) {
  return { ...structuredClone(FIXTURE.programMeta), ...overrides };
}

/**
 * Write the program into both replicas over whatever the page currently holds,
 * then reload onto it. `waitFor` is the suite's own post-reload boot wait.
 */
export async function installSeedProgram(page, { key = "repforge_v1", waitFor } = {}) {
  const base = await page.evaluate((k) => JSON.parse(localStorage.getItem(k) || "{}"), key);
  const blob = {
    ...base,
    program: seedProgram(),
    programMeta: seedProgramMeta(),
    log: Array.isArray(base.log) ? base.log : [],
  };
  await page.evaluate(
    async ({ k, state }) => {
      localStorage.setItem(k, JSON.stringify(state));
      const db = await new Promise((res, rej) => {
        const r = indexedDB.open("repforge", 1);
        r.onupgradeneeded = () => r.result.createObjectStore("kv");
        r.onsuccess = () => res(r.result);
        r.onerror = () => rej(r.error);
      });
      await new Promise((res, rej) => {
        const tx = db.transaction("kv", "readwrite");
        tx.objectStore("kv").put(state, k);
        tx.oncomplete = () => res();
        tx.onerror = () => rej(tx.error);
      });
      db.close();
    },
    { k: key, state: blob }
  );
  await page.reload({ waitUntil: "domcontentloaded" });
  if (waitFor) await waitFor(page);
  return blob;
}
